apiRules:
- include:
    uidRegex: StrangeLand
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
- exclude:
    uidRegex: Unity.
    type: Namespace
- exclude:
    uidRegex: UnityEditor.
    type: Namespace